// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ScrapeInput struct {
	Pointer   string `json:"pointer"`
	TargetURL string `json:"target_url"`
}

type ScrapeOutput struct {
	Elements []string `json:"elements"`
}
